---
title: "Bike Data Model Building"
author: "Mark Barkell"
date: "January 13, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Executative Summary

The Bike Data

```{r downloadsomedata}
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/00275/Bike-Sharing-Dataset.zip"
zipFileLocation = "./Bike-Sharing-Data.zip"
if (!file.exists(zipFileLocation)) {
  download.file(url, zipFileLocation)
}
dayCsvFileName = "./day.csv"
hourCsvFileName = "./hour.csv"
if (!file.exists(dayCsvFileName)) {
  unzip(zipfile = zipFileLocation)
}

dayData <- read.csv(file = dayCsvFileName)
hourData <- read.csv(file = hourCsvFileName)


```

```{r tidifydata}
weekdayFactor <- as.factor(c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"))
seasonFactor <- as.factor(c("spring", "summer", "fall", "winter"))
weathersitFactor <- as.factor(c("ClearOrFewCloudsOrPartyCloudy", "MistCloudyOrMistBrokenCloudsOrMistFewCloudsOrMist", "LightSnowOrLightRainOrThunderStormOrScatteredCloudsOrLightRainOrScatteredClouds", "HeavyRainOrIcePalletsOrThunderstormOrMistOrSnowOrFog"))
dayData$season <- seasonFactor[dayData$season]
hourData$season <- seasonFactor[hourData$season]
dayData$weathersit <- weathersitFactor[dayData$weathersit]
hourData$weathersit <- weathersitFactor[hourData$weathersit]
dayData$weekday <- as.factor(1 + dayData$weekday)
hourData$weekday <- as.factor(1 + hourData$weekday)
```

```{r libraryCalls, ignore=TRUE}
library(caret)
```

```{r splitupthedata}
# openssl rand -hex 4
set.seed(0x86d36f8)
dayPart <- createDataPartition(y = dayData$casual, p = .9, list=FALSE)
hourPart <- createDataPartition(y = hourData$casual, p =  .9, list=FALSE)
trainingDay <- dayData[dayPart,]
testingDay <- dayData[-dayPart,]
trainingHour <- hourData[hourPart,]
testingHour <- hourData[-hourPart,]
```

```{r worthyparameters}
worthyDayParameters <- c("season", "mnth", "holiday", "weekday", "workingday", "weathersit", "temp", "atemp", "hum", "windspeed")
worthyHourParameters <- c("season", "mnth", "holiday", "weekday", "workingday", "weathersit", "temp", "atemp", "hum", "windspeed", "hr")
```

```{r training}
treeBagDayModel <- caret::train(y = (trainingDay$casual+1)/(trainingDay$registered+1), x = trainingDay[,worthyDayParameters], method = "treebag", preProcess = c("scale", "center", "BoxCox"))
treeBagHourModel <- caret::train(y = (trainingHour$casual+1)/(trainingHour$registered+1), x = trainingHour[,worthyHourParameters], method = "treebag", preProcess = c("scale", "center", "BoxCox"))
```

```{r trainingResdPlotDay}
resdsDay <-  predict(treeBagDayModel, trainingDay[,worthyDayParameters]) - (trainingDay$casual+1)/(trainingDay$registered+1)
plot(y = resdsDay, x = trainingDay$dteday)
```

```{r trainingResdPlotHourByDay}
resdsHour <- predict(treeBagHourModel, trainingHour[,worthyHourParameters]) - (trainingHour$casual+1)/(trainingHour$registered + 1)
plot(y = resdsHour, x = trainingHour$dteday )
```

```{r trainingResdPlotHour}
#as.POSIXct
datetimeFormat <- "%Y-%m-%dT%H:%M"
datesWithHours <- as.POSIXct(paste(as.character(trainingHour$dteday) , "T" , as.character(trainingHour$hr), ":00"), datetimeFormat )
plot(y = resdsHour, x = datesWithHours )
```


```{r resdsHourHour}
plot(y = resdsHour, x = trainingHour$hr)
```

## References

1. [Bike Sharing Dataset Data Set](https://archive.ics.uci.edu/ml/datasets/Bike+Sharing+Dataset#)

